version: '3'

services:
  server:
    build: ./backend
    command: npm run dev
    ports:
      - "3333:3333"
    environment:
      DB_DATABASE: mydb
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: ep-postgres
      DB_PORT: 5432
    volumes:
      - ./backend:/usr/app
    links:
      - ep-postgres
    networks:
      - EP-BD

  ep-postgres:
    image: postgres:11.5
    container_name: ep-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - "15432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./db/ex1-a.sql:/docker-entrypoint-initdb.d/02_ex1-a.sql
      - ./db/ex1-b.sql:/docker-entrypoint-initdb.d/03_ex1-b.sql
      - ./db/ex1-c.sql:/docker-entrypoint-initdb.d/04_ex1-c.sql
      - ./db/ex1-d.sql:/docker-entrypoint-initdb.d/05_ex1-d.sql

    restart: always
    networks:
      - EP-BD
    
  front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    links:
      - server
    networks:
      - EP-BD

volumes: 
  db:
    driver: local

networks:
  EP-BD:
    driver: bridge