version: '3'

services:
  server:
    build: ./backend
    command: npm run dev
    ports:
      - "3333:3333"
    environment:
      DB_DATABASE: mydb
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: ep-postgres
      DB_PORT: 5432
    volumes:
      - ./backend:/usr/app
    links:
      - ep-postgres
    networks:
      - EP-BD

  ep-postgres:
    image: postgres:11.5
    container_name: ep-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - "15432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./db/Conflitos.sql:/docker-entrypoint-initdb.d/02_Conflitos.sql
      - ./db/Territoriais.sql:/docker-entrypoint-initdb.d/03_Territoriais.sql
      - ./db/Religiosos.sql:/docker-entrypoint-initdb.d/04_Religiosos.sql
      - ./db/Economicos.sql:/docker-entrypoint-initdb.d/05_Economicos.sql
      - ./db/Raciais.sql:/docker-entrypoint-initdb.d/06_Raciais.sql
      - ./db/Conflito_paisesAfetados.sql:/docker-entrypoint-initdb.d/07_Conflito_paisesAfetados.sql
      - ./db/Combatentes.sql:/docker-entrypoint-initdb.d/08_Combatentes.sql
      - ./db/GruposArmados.sql:/docker-entrypoint-initdb.d/09_GruposArmados.sql
      - ./db/Organizacao.sql:/docker-entrypoint-initdb.d/10_Organizacao.sql
      - ./db/OrganizacoesMediadoras.sql:/docker-entrypoint-initdb.d/11_OrganizacoesMediadoras.sql
    restart: always
    networks:
      - EP-BD
    
  front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    links:
      - server
    networks:
      - EP-BD

volumes: 
  db:
    driver: local

networks:
  EP-BD:
    driver: bridge