version: '3'

services:
  server:
    build: ./backend
    ports:
      - "3333:3333"
    environment:
      DB_DATABASE: test
      DB_USER: test
      DB_PASSWORD: test
      DB_HOST: db
    volumes:
      - ./backend:/usr/src/app
    links:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    
  front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    links:
      - server

volumes: 
  db:
    driver: local