version: '3'

services:
  server:
    build: ./backend
    ports:
      - "3333:3333"
    environment:
      DB_DATABASE: test
      DB_USER: test
      DB_PASSWORD: test
      DB_HOST: db
    volumes:
      - ./backend:/usr/src/app
    links:
      - ep-postgres
    networks:
      - EP-BD

  ep-postgres:
    image: postgres:11.5
    container_name: ep-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - "15432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - EP-BD
    
  front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    links:
      - server
    networks:
      - EP-BD

volumes: 
  db:
    driver: local

networks:
  EP-BD:
    driver: bridge