-- MySQL Script generated by MySQL Workbench
-- Mon Nov 14 22:06:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Conflitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conflitos` (
  `CodigoNum` INT NOT NULL AUTO_INCREMENT,
  `numMortos` INT NOT NULL,
  `NomeLugarCausa` VARCHAR(100) NOT NULL,
  `NumFeridos` INT NOT NULL,
  `TipoConflito` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CodigoNum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Territoriais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Territoriais` (
  `Conflitos_CodigoNum` INT NOT NULL,
  `RegioesAfetadas` VARCHAR(100) NOT NULL,
  FOREIGN KEY (`Conflitos_CodigoNum`) REFERENCES `mydb`.`Conflitos` (`CodigoNum`),
  PRIMARY KEY (`Conflitos_CodigoNum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Religiosos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Religiosos` (
  `Conflitos_CodigoNum` INT NOT NULL,
  `ReligioesAfetadas` VARCHAR(100) NOT NULL,
  FOREIGN KEY (`Conflitos_CodigoNum`) REFERENCES `mydb`.`Conflitos` (`CodigoNum`),
  PRIMARY KEY (`Conflitos_CodigoNum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Econômicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Economicos` (
  `Conflitos_CodigoNum` INT NOT NULL,
  `MateriasPrimas` VARCHAR(100) NOT NULL,
  FOREIGN KEY (`Conflitos_CodigoNum`) REFERENCES `mydb`.`Conflitos` (`CodigoNum`),
  PRIMARY KEY (`Conflitos_CodigoNum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Raciais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Raciais` (
  `Conflitos_CodigoNum` INT NOT NULL,
  `EtniasAfetadas` VARCHAR(100) NULL,
  FOREIGN KEY (`Conflitos_CodigoNum`) REFERENCES `mydb`.`Conflitos` (`CodigoNum`),
  PRIMARY KEY (`Conflitos_CodigoNum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conflito_paisesAfetados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conflito_paisesAfetados` (
  `Conflitos_CodigoNum` INT NOT NULL,
  `PaisAfetado` VARCHAR(100) NOT NULL,
  FOREIGN KEY (`Conflitos_CodigoNum`) REFERENCES `mydb`.`Conflitos` (`CodigoNum`),
  PRIMARY KEY (`Conflitos_CodigoNum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Combatentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Combatentes` (
  `Codigo` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GruposArmados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GruposArmados` (
  `Combatentes_Codigo` INT NOT NULL,
  `NumTotalBaixas` INT NOT NULL,
  FOREIGN KEY (`Combatentes_Codigo`) REFERENCES `mydb`.`Combatentes` (`Codigo`),
  PRIMARY KEY (`Combatentes_Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Organizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Organizacao` (
  `CodigoOrg` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`CodigoOrg`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrganizacoesMediadoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrganizacoesMediadoras` (
  `Combatentes_Codigo` INT NOT NULL,
  `Organizacao_CodigoOrg` INT NOT NULL,
  `NumPessoas` INT NOT NULL,
  `TipoOrganizacao` VARCHAR(100) NOT NULL,
  FOREIGN KEY (`Combatentes_Codigo`) REFERENCES `mydb`.`Combatentes` (`Codigo`),
  PRIMARY KEY (`Combatentes_Codigo`),
  FOREIGN KEY (`Organizacao_CodigoOrg`) REFERENCES `mydb`.`Organizacao` (`CodigoOrg`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OganizacoesMediadoras_TipoAjuda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OganizacoesMediadoras_TipoAjuda` (
  `OrganizacoesMediadoras_CodCombatente` INT NOT NULL,
  `TipoAjuda` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`OrganizacoesMediadoras_CodCombatente`),
  FOREIGN KEY (`OrganizacoesMediadoras_CodCombatente`) REFERENCES `mydb`.`OrganizacoesMediadoras` (`Combatentes_Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conflitos_sao_intervidos_Combatentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conflitos_sao_intervidos_Combatentes` (
  `Conflitos_CodigoNum` INT NOT NULL,
  `Combatentes_Codigo` INT NOT NULL,
  FOREIGN KEY (`Conflitos_CodigoNum`) REFERENCES `mydb`.`Conflitos` (`CodigoNum`),
  FOREIGN KEY (`Combatentes_Codigo`) REFERENCES `mydb`.`Combatentes` (`Codigo`),
  PRIMARY KEY (`Conflitos_CodigoNum`, `Combatentes_Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrganizacoesMediadoras_participam_Conflitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrganizacoesMediadoras_participam_Conflitos` (
  `OrganizacoesMediadoras_CodigoOrganizacao` INT NOT NULL,
  `Conflitos_CodigoNum` INT NOT NULL,
  `DataIncorporacao` DATE NOT NULL,
  `DataSaida` DATE NOT NULL,
  PRIMARY KEY (`OrganizacoesMediadoras_CodigoOrganizacao`, `Conflitos_CodigoNum`),
  FOREIGN KEY (`OrganizacoesMediadoras_CodigoOrganizacao`) REFERENCES `mydb`.`OrganizacoesMediadoras` (`Combatentes_Codigo`),
  FOREIGN KEY (`Conflitos_CodigoNum`) REFERENCES `mydb`.`Conflitos` (`CodigoNum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GruposArmados_participam_Conflitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GruposArmados_participam_Conflitos` (
  `GruposArmados_Combatentes_Codigo` INT NOT NULL,
  `Conflitos_CodigoNum` INT NOT NULL,
  `DataIncorporacao` DATE NOT NULL,
  `DataSaida` DATE NOT NULL,
  PRIMARY KEY (`GruposArmados_Combatentes_Codigo`, `Conflitos_CodigoNum`),
  FOREIGN KEY (`GruposArmados_Combatentes_Codigo`) REFERENCES `mydb`.`GruposArmados` (`Combatentes_Codigo`),
  FOREIGN KEY (`Conflitos_CodigoNum`) REFERENCES `mydb`.`Conflitos` (`CodigoNum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Traficantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Traficantes` (
  `Nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoArma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoArma` (
  `Nome` VARCHAR(100) NOT NULL,
  `IndCapDest` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Traficantes_fornecem_TipoArma_GruposArmados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Traficantes_fornecem_TipoArma_GruposArmados` (
  `Traficantes_Nome` VARCHAR(100) NOT NULL,
  `TipoArma_Nome` VARCHAR(100) NOT NULL,
  `GruposArmados_CodCombatente` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`Traficantes_Nome`, `TipoArma_Nome`, `GruposArmados_CodCombatente`),
  FOREIGN KEY (`Traficantes_Nome`) REFERENCES `mydb`.`Traficantes` (`Nome`),
  FOREIGN KEY (`TipoArma_Nome`) REFERENCES `mydb`.`TipoArma` (`Nome`),
  FOREIGN KEY (`GruposArmados_CodCombatente`) REFERENCES `mydb`.`GruposArmados` (`Combatentes_Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Divisao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Divisao` (
  `CodConsecutivo` INT NOT NULL,
  `GruposArmados_CodCombatente` INT NOT NULL,
  `NumBaixas` INT NOT NULL,
  `Barcos` INT NOT NULL,
  `Tanques` INT NOT NULL,
  `Avioes` INT NOT NULL,
  `Homens` INT NOT NULL,
  PRIMARY KEY (`CodConsecutivo`, `GruposArmados_CodCombatente`),
  FOREIGN KEY (`GruposArmados_CodCombatente`) REFERENCES `mydb`.`GruposArmados` (`Combatentes_Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ChefeMilitar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ChefeMilitar` (
  `Codigo` INT NOT NULL AUTO_INCREMENT,
  `Divisao_CodConsecutivo` INT NOT NULL,
  `Divisao_GruposArmados_CodCombatente` INT NOT NULL,
  `FaixaHierarquica` VARCHAR(100) NOT NULL,
  `LiderPoliticoObedece` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Codigo`),
  FOREIGN KEY (Divisao_CodConsecutivo) REFERENCES `mydb`.`Divisao` (`CodConsecutivo`),
  FOREIGN KEY (Divisao_GruposArmados_CodCombatente) REFERENCES `mydb`.`Divisao` (`GruposArmados_CodCombatente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LiderPolitico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LiderPolitico` (
  `Nome` VARCHAR(100) NOT NULL,
  `GruposArmados_CodCombatente` INT NOT NULL,
  `DescApoios` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Nome`, `GruposArmados_CodCombatente`),
  FOREIGN KEY (`GruposArmados_CodCombatente`) REFERENCES `mydb`.`GruposArmados` (`Combatentes_Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Organizacao_dialoga_com_LiderPolitico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Organizacao_dialoga_com_LiderPolitico` (
  `Organizacao_CodigoOrg` INT NOT NULL,
  `LiderPolitico_Nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Organizacao_CodigoOrg`, `LiderPolitico_Nome`),
  FOREIGN KEY (`Organizacao_CodigoOrg`) REFERENCES `mydb`.`Organizacao` (`CodigoOrg`),
  FOREIGN KEY (`LiderPolitico_Nome`) REFERENCES `mydb`.`LiderPolitico` (`Nome`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
